language: ruby
rbenv:
- 2.5.3
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: ENV[MAP_API_KEY]
  app: go-local-maps-api
  on:
    repo: Team-Go-Local/go_local_microservice
    branch: main
